update

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -29,20 +29,23 @@ jobs:
       - name: Generate and check  configs
         run: yarn workspace @parent/core run generate
 
-      - name: Check Status2
-        run: | 
-          echo "Checking files"
-          if [ $? -eq 1 ]; then
-          echo "Error occured in generating files."
-            exit 1
-          else
-            status=$(git status --porcelain)
-            if [ -n "$status" ]; then
-              echo "Following config files have mismatched changes in PR. Please generate"
-              echo "$status"
-              exit 1
-            else
-              echo "Config files are up to date."
-              exit 0
-            fi
-          fi
+      - name: Generate and check computed configs
+        run: $GITHUB_WORKSPACE/parent/core/bin/generate.sh  
+        
+      # - name: Check Status2
+      #   run: | 
+      #     echo "Checking files"
+      #     if [ $? -eq 1 ]; then
+      #     echo "Error occured in generating files."
+      #       exit 1
+      #     else
+      #       status=$(git status --porcelain)
+      #       if [ -n "$status" ]; then
+      #         echo "Following config files have mismatched changes in PR. Please generate"
+      #         echo "$status"
+      #         exit 1
+      #       else
+      #         echo "Config files are up to date."
+      #         exit 0
+      #       fi
+      #     fi
